/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#131313',
        'on-secondary': '#313030',
        'on-surface': '#e5e2e1',
        'secondary-fixed': '#e5e2e1',
        'inverse-on-surface': '#303030',
        'surface-container-highest': '#353535',
        'on-secondary-fixed-variant': '#474646',
        'on-primary-fixed-variant': '#454747',
        'on-error': '#690005',
        'primary-fixed-dim': '#c6c6c7',
        'secondary-container': '#4a4949',
        surface: '#131313',
        'inverse-primary': '#5d5f5f',
        'surface-container': '#202020',
        'on-tertiary': '#213145',
        'surface-container-high': '#2a2a2a',
        'on-primary-container': '#636565',
        'on-tertiary-fixed-variant': '#38485d',
        'on-primary-fixed': '#1a1c1c',
        'inverse-surface': '#e5e2e1',
        'on-error-container': '#ffdad6',
        error: '#ffb4ab',
        'surface-bright': '#393939',
        primary: '#ffffff',
        'primary-container': '#e2e2e2',
        'tertiary-container': '#d3e4fe',
        'on-surface-variant': '#c4c7c8',
        'primary-fixed': '#e2e2e2',
        outline: '#8e9192',
        'tertiary-fixed': '#d3e4fe',
        'surface-container-low': '#1b1b1c',
        'on-secondary-fixed': '#1c1b1b',
        'tertiary-fixed-dim': '#b7c8e1',
        'on-tertiary-fixed': '#0b1c30',
        'outline-variant': '#444748',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#c8c6c5',
        'surface-variant': '#353535',
        'on-secondary-container': '#bab8b7',
        'on-background': '#e5e2e1',
        tertiary: '#ffffff',
        'on-primary': '#2f3131',
        'surface-tint': '#c6c6c7',
        'surface-dim': '#131313',
        'on-tertiary-container': '#56657c',
        'surface-container-lowest': '#0e0e0e',
        secondary: '#c8c6c5',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'section-gap': '128px',
        'container-max': '1440px',
        unit: '8px',
        gutter: '24px',
        'margin-mobile': '24px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'headline-sm': ['Inter'],
        'display-lg-mobile': ['Inter'],
        'label-sm': ['Geist'],
        'body-md': ['Inter'],
        'headline-md': ['Inter'],
        'body-lg': ['Inter'],
        'display-lg': ['Inter'],
      },
      fontSize: {
        'headline-sm': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '500' },
        ],
        'display-lg-mobile': [
          '40px',
          { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '300' },
        ],
        'label-sm': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' },
        ],
        'body-md': [
          '16px',
          { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' },
        ],
        'headline-md': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '400' },
        ],
        'body-lg': [
          '18px',
          { lineHeight: '28px', letterSpacing: '0em', fontWeight: '400' },
        ],
        'display-lg': [
          '72px',
          { lineHeight: '72px', letterSpacing: '-0.04em', fontWeight: '300' },
        ],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
